.TH DNS-EXPORT 1
.SH NAME
dns-export \- export dns info to syslog server
.SH SYNOPSIS
.B dns-export
[\fB\-r\fR \fIfile.pcap\fR]
[\fB\-i\fR \fIinterface\fR]
[\fB\-s\fR \fIsyslog-server\fR]
[\fB\-t\fR \fIseconds\fR]
.SH DESCRIPTION
.B dns-export
This program creates statistics about DNS communication and exports them to a syslog server.
.SH OPTIONS
.TP
.BR \-r =file.pcap
Application will process a specified static PCAP file.
.TP
.BR \-i =interface
Application will listen on a live interface
.TP
.BR \-s =syslog-server
Hostname/IPv4/IPv6 address of the syslog server.
.TP
.BR \-t =seconds
Time of the interval between dispatching of the statistics to syslog server in seconds.